[workspace]
resolver = "2"
members = [
    "crates/pebble",
    "xtask",
]

[workspace.dependencies]
tempfile = "=3.25.0"
toml = "0.9"
color-eyre = "0.6"
serde = "1.0.228"
clap = "4.5.59"
nanoid = "0.4.0"
chrono = { version = "0.4.43", features = ["serde"] }
serde_json = "1.0.149"
serde_yaml = "0.9.34"
assert_cmd = "2.1.2"
predicates = "3.1.4"
const_format = "0.2"

[workspace.lints.clippy]
cognitive_complexity = "warn"
type_complexity = "warn"
too_many_arguments = "warn"
too_many_lines = "warn"
large_enum_variant = "warn"
struct_excessive_bools = "warn"
